// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using migracio_api.Data;

#nullable disable

namespace migracio_api.Migrations
{
    [DbContext(typeof(NominaContext))]
    partial class NominaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedModels.Deduccion", b =>
                {
                    b.Property<decimal>("EmpleadoId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EmpleadoId1")
                        .HasColumnType("int");

                    b.Property<decimal>("IR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Inatec")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InssLaboral")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InssPatronal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Nombre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtrasDeduccion")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("EmpleadoId1");

                    b.ToTable("deducciones");
                });

            modelBuilder.Entity("SharedModels.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"));

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NInss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("cierradeContrato")
                        .HasColumnType("datetime2");

                    b.HasKey("EmpleadoId");

                    b.ToTable("empleados");
                });

            modelBuilder.Entity("SharedModels.Ingreso", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"));

                    b.Property<decimal?>("Bono")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Comision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmpleadoId1")
                        .HasColumnType("int");

                    b.Property<decimal>("HoraExtra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Nombre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtrosIngresos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RiesgoNocturnidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("EmpleadoId1");

                    b.ToTable("ingresos");
                });

            modelBuilder.Entity("SharedModels.Nomina", b =>
                {
                    b.Property<decimal>("EmpleadoId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Bono")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Comision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EmpleadoId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HoraExtra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Inatec")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InssLaboral")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InssPatronal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OtrasDeduccion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtrosIngresos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemuneracionBruta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemuneracionEmpresaarial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemuneracionNeta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RiesgoNocturnidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("EmpleadoId1");

                    b.ToTable("nominas");
                });

            modelBuilder.Entity("SharedModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SharedModels.Deduccion", b =>
                {
                    b.HasOne("SharedModels.Empleado", "Empleado")
                        .WithMany("Deducciones")
                        .HasForeignKey("EmpleadoId1");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("SharedModels.Ingreso", b =>
                {
                    b.HasOne("SharedModels.Empleado", "Empleado")
                        .WithMany("Ingresos")
                        .HasForeignKey("EmpleadoId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("SharedModels.Nomina", b =>
                {
                    b.HasOne("SharedModels.Empleado", "Empleado")
                        .WithMany("Nominas")
                        .HasForeignKey("EmpleadoId1");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("SharedModels.Empleado", b =>
                {
                    b.Navigation("Deducciones");

                    b.Navigation("Ingresos");

                    b.Navigation("Nominas");
                });
#pragma warning restore 612, 618
        }
    }
}
